Update reddit-scraper.py
added missing information to function argument that I forgot to add, at line 201
TypeError: data_to_db() missing 1 required positional argument: 'key_data'